services:
  db:
    image: postgres:16
    container_name: expense_db
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - expense_pgdata:/var/lib/postgresql/data

volumes:
  expense_pgdata:
